# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.6
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_api', [dirname(__file__)])
        except ImportError:
            import _api
            return _api
        if fp is not None:
            try:
                _mod = imp.load_module('_api', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _api = swig_import_helper()
    del swig_import_helper
else:
    import _api
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



_api.ePdfField_PushButton_swigconstant(_api)
ePdfField_PushButton = _api.ePdfField_PushButton

_api.ePdfField_CheckBox_swigconstant(_api)
ePdfField_CheckBox = _api.ePdfField_CheckBox

_api.ePdfField_RadioButton_swigconstant(_api)
ePdfField_RadioButton = _api.ePdfField_RadioButton

_api.ePdfField_TextField_swigconstant(_api)
ePdfField_TextField = _api.ePdfField_TextField

_api.ePdfField_ComboBox_swigconstant(_api)
ePdfField_ComboBox = _api.ePdfField_ComboBox

_api.ePdfField_ListBox_swigconstant(_api)
ePdfField_ListBox = _api.ePdfField_ListBox

_api.ePdfField_Signature_swigconstant(_api)
ePdfField_Signature = _api.ePdfField_Signature

_api.ePdfField_Unknown_swigconstant(_api)
ePdfField_Unknown = _api.ePdfField_Unknown

_api.ePdfError_ErrOk_swigconstant(_api)
ePdfError_ErrOk = _api.ePdfError_ErrOk

_api.ePdfError_TestFailed_swigconstant(_api)
ePdfError_TestFailed = _api.ePdfError_TestFailed

_api.ePdfError_InvalidHandle_swigconstant(_api)
ePdfError_InvalidHandle = _api.ePdfError_InvalidHandle

_api.ePdfError_FileNotFound_swigconstant(_api)
ePdfError_FileNotFound = _api.ePdfError_FileNotFound

_api.ePdfError_InvalidDeviceOperation_swigconstant(_api)
ePdfError_InvalidDeviceOperation = _api.ePdfError_InvalidDeviceOperation

_api.ePdfError_UnexpectedEOF_swigconstant(_api)
ePdfError_UnexpectedEOF = _api.ePdfError_UnexpectedEOF

_api.ePdfError_OutOfMemory_swigconstant(_api)
ePdfError_OutOfMemory = _api.ePdfError_OutOfMemory

_api.ePdfError_ValueOutOfRange_swigconstant(_api)
ePdfError_ValueOutOfRange = _api.ePdfError_ValueOutOfRange

_api.ePdfError_InternalLogic_swigconstant(_api)
ePdfError_InternalLogic = _api.ePdfError_InternalLogic

_api.ePdfError_InvalidEnumValue_swigconstant(_api)
ePdfError_InvalidEnumValue = _api.ePdfError_InvalidEnumValue

_api.ePdfError_PageNotFound_swigconstant(_api)
ePdfError_PageNotFound = _api.ePdfError_PageNotFound

_api.ePdfError_NoPdfFile_swigconstant(_api)
ePdfError_NoPdfFile = _api.ePdfError_NoPdfFile

_api.ePdfError_NoXRef_swigconstant(_api)
ePdfError_NoXRef = _api.ePdfError_NoXRef

_api.ePdfError_NoTrailer_swigconstant(_api)
ePdfError_NoTrailer = _api.ePdfError_NoTrailer

_api.ePdfError_NoNumber_swigconstant(_api)
ePdfError_NoNumber = _api.ePdfError_NoNumber

_api.ePdfError_NoObject_swigconstant(_api)
ePdfError_NoObject = _api.ePdfError_NoObject

_api.ePdfError_NoEOFToken_swigconstant(_api)
ePdfError_NoEOFToken = _api.ePdfError_NoEOFToken

_api.ePdfError_InvalidTrailerSize_swigconstant(_api)
ePdfError_InvalidTrailerSize = _api.ePdfError_InvalidTrailerSize

_api.ePdfError_InvalidLinearization_swigconstant(_api)
ePdfError_InvalidLinearization = _api.ePdfError_InvalidLinearization

_api.ePdfError_InvalidDataType_swigconstant(_api)
ePdfError_InvalidDataType = _api.ePdfError_InvalidDataType

_api.ePdfError_InvalidXRef_swigconstant(_api)
ePdfError_InvalidXRef = _api.ePdfError_InvalidXRef

_api.ePdfError_InvalidXRefStream_swigconstant(_api)
ePdfError_InvalidXRefStream = _api.ePdfError_InvalidXRefStream

_api.ePdfError_InvalidXRefType_swigconstant(_api)
ePdfError_InvalidXRefType = _api.ePdfError_InvalidXRefType

_api.ePdfError_InvalidPredictor_swigconstant(_api)
ePdfError_InvalidPredictor = _api.ePdfError_InvalidPredictor

_api.ePdfError_InvalidStrokeStyle_swigconstant(_api)
ePdfError_InvalidStrokeStyle = _api.ePdfError_InvalidStrokeStyle

_api.ePdfError_InvalidHexString_swigconstant(_api)
ePdfError_InvalidHexString = _api.ePdfError_InvalidHexString

_api.ePdfError_InvalidStream_swigconstant(_api)
ePdfError_InvalidStream = _api.ePdfError_InvalidStream

_api.ePdfError_InvalidStreamLength_swigconstant(_api)
ePdfError_InvalidStreamLength = _api.ePdfError_InvalidStreamLength

_api.ePdfError_InvalidKey_swigconstant(_api)
ePdfError_InvalidKey = _api.ePdfError_InvalidKey

_api.ePdfError_InvalidName_swigconstant(_api)
ePdfError_InvalidName = _api.ePdfError_InvalidName

_api.ePdfError_InvalidEncryptionDict_swigconstant(_api)
ePdfError_InvalidEncryptionDict = _api.ePdfError_InvalidEncryptionDict

_api.ePdfError_InvalidPassword_swigconstant(_api)
ePdfError_InvalidPassword = _api.ePdfError_InvalidPassword

_api.ePdfError_InvalidFontFile_swigconstant(_api)
ePdfError_InvalidFontFile = _api.ePdfError_InvalidFontFile

_api.ePdfError_InvalidContentStream_swigconstant(_api)
ePdfError_InvalidContentStream = _api.ePdfError_InvalidContentStream

_api.ePdfError_UnsupportedFilter_swigconstant(_api)
ePdfError_UnsupportedFilter = _api.ePdfError_UnsupportedFilter

_api.ePdfError_UnsupportedFontFormat_swigconstant(_api)
ePdfError_UnsupportedFontFormat = _api.ePdfError_UnsupportedFontFormat

_api.ePdfError_ActionAlreadyPresent_swigconstant(_api)
ePdfError_ActionAlreadyPresent = _api.ePdfError_ActionAlreadyPresent

_api.ePdfError_WrongDestinationType_swigconstant(_api)
ePdfError_WrongDestinationType = _api.ePdfError_WrongDestinationType

_api.ePdfError_MissingEndStream_swigconstant(_api)
ePdfError_MissingEndStream = _api.ePdfError_MissingEndStream

_api.ePdfError_Date_swigconstant(_api)
ePdfError_Date = _api.ePdfError_Date

_api.ePdfError_Flate_swigconstant(_api)
ePdfError_Flate = _api.ePdfError_Flate

_api.ePdfError_FreeType_swigconstant(_api)
ePdfError_FreeType = _api.ePdfError_FreeType

_api.ePdfError_SignatureError_swigconstant(_api)
ePdfError_SignatureError = _api.ePdfError_SignatureError

_api.ePdfError_MutexError_swigconstant(_api)
ePdfError_MutexError = _api.ePdfError_MutexError

_api.ePdfError_UnsupportedImageFormat_swigconstant(_api)
ePdfError_UnsupportedImageFormat = _api.ePdfError_UnsupportedImageFormat

_api.ePdfError_CannotConvertColor_swigconstant(_api)
ePdfError_CannotConvertColor = _api.ePdfError_CannotConvertColor

_api.ePdfError_NotImplemented_swigconstant(_api)
ePdfError_NotImplemented = _api.ePdfError_NotImplemented

_api.ePdfError_DestinationAlreadyPresent_swigconstant(_api)
ePdfError_DestinationAlreadyPresent = _api.ePdfError_DestinationAlreadyPresent

_api.ePdfError_ChangeOnImmutable_swigconstant(_api)
ePdfError_ChangeOnImmutable = _api.ePdfError_ChangeOnImmutable

_api.ePdfError_NotCompiled_swigconstant(_api)
ePdfError_NotCompiled = _api.ePdfError_NotCompiled

_api.ePdfError_Unknown_swigconstant(_api)
ePdfError_Unknown = _api.ePdfError_Unknown
class PdfError(Exception):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, PdfError, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, PdfError, name)
    __repr__ = _swig_repr

    def what(self):
        return _api.PdfError_what(self)

    def GetError(self):
        return _api.PdfError_GetError(self)

    def ErrorMessage(self, eCode):
        return _api.PdfError_ErrorMessage(self, eCode)
    __swig_destroy__ = _api.delete_PdfError
    __del__ = lambda self: None

    def __init__(self):
        this = _api.new_PdfError()
        try:
            self.this.append(this)
        except:
            self.this = this
PdfError_swigregister = _api.PdfError_swigregister
PdfError_swigregister(PdfError)

class PdfMemDocument(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, PdfMemDocument, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, PdfMemDocument, name)
    __repr__ = _swig_repr

    def __init__(self, arg2):
        this = _api.new_PdfMemDocument(arg2)
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _api.delete_PdfMemDocument
    __del__ = lambda self: None

    def GetPageCount(self):
        return _api.PdfMemDocument_GetPageCount(self)

    def GetPage(self, arg2):
        return _api.PdfMemDocument_GetPage(self, arg2)

    def Write(self, arg2):
        return _api.PdfMemDocument_Write(self, arg2)
PdfMemDocument_swigregister = _api.PdfMemDocument_swigregister
PdfMemDocument_swigregister(PdfMemDocument)

class PdfPage(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, PdfPage, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, PdfPage, name)
    __repr__ = _swig_repr

    def __init__(self, pObject, listOfParents):
        this = _api.new_PdfPage(pObject, listOfParents)
        try:
            self.this.append(this)
        except:
            self.this = this

    def GetNumFields(self):
        return _api.PdfPage_GetNumFields(self)

    def GetField(self, arg2):
        return _api.PdfPage_GetField(self, arg2)

    def GetPageNumber(self):
        return _api.PdfPage_GetPageNumber(self)
    __swig_destroy__ = _api.delete_PdfPage
    __del__ = lambda self: None
PdfPage_swigregister = _api.PdfPage_swigregister
PdfPage_swigregister(PdfPage)

class PdfField(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, PdfField, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, PdfField, name)
    __repr__ = _swig_repr

    def __init__(self, arg2):
        this = _api.new_PdfField(arg2)
        try:
            self.this.append(this)
        except:
            self.this = this

    def GetFieldName(self):
        return _api.PdfField_GetFieldName(self)

    def GetPage(self):
        return _api.PdfField_GetPage(self)

    def SetFieldName(self, arg2):
        return _api.PdfField_SetFieldName(self, arg2)

    def GetType(self):
        return _api.PdfField_GetType(self)
    __swig_destroy__ = _api.delete_PdfField
    __del__ = lambda self: None
PdfField_swigregister = _api.PdfField_swigregister
PdfField_swigregister(PdfField)

class PdfTextField(PdfField):
    __swig_setmethods__ = {}
    for _s in [PdfField]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, PdfTextField, name, value)
    __swig_getmethods__ = {}
    for _s in [PdfField]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, PdfTextField, name)
    __repr__ = _swig_repr

    def __init__(self, arg2):
        this = _api.new_PdfTextField(arg2)
        try:
            self.this.append(this)
        except:
            self.this = this

    def SetText(self, arg2):
        return _api.PdfTextField_SetText(self, arg2)

    def GetText(self):
        return _api.PdfTextField_GetText(self)

    def SetMaxLen(self, nMaxLen):
        return _api.PdfTextField_SetMaxLen(self, nMaxLen)

    def GetMaxLen(self):
        return _api.PdfTextField_GetMaxLen(self)
    __swig_destroy__ = _api.delete_PdfTextField
    __del__ = lambda self: None
PdfTextField_swigregister = _api.PdfTextField_swigregister
PdfTextField_swigregister(PdfTextField)

class PdfListField(PdfField):
    __swig_setmethods__ = {}
    for _s in [PdfField]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, PdfListField, name, value)
    __swig_getmethods__ = {}
    for _s in [PdfField]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, PdfListField, name)
    __repr__ = _swig_repr

    def __init__(self, arg2):
        this = _api.new_PdfListField(arg2)
        try:
            self.this.append(this)
        except:
            self.this = this

    def InsertItem(self, *args):
        return _api.PdfListField_InsertItem(self, *args)

    def GetItem(self, arg2):
        return _api.PdfListField_GetItem(self, arg2)

    def RemoveItem(self, arg2):
        return _api.PdfListField_RemoveItem(self, arg2)

    def GetItemCount(self):
        return _api.PdfListField_GetItemCount(self)

    def SetSelectedItem(self, arg2):
        return _api.PdfListField_SetSelectedItem(self, arg2)

    def GetSelectedItem(self):
        return _api.PdfListField_GetSelectedItem(self)
    __swig_destroy__ = _api.delete_PdfListField
    __del__ = lambda self: None
PdfListField_swigregister = _api.PdfListField_swigregister
PdfListField_swigregister(PdfListField)

class PdfComboBox(PdfListField):
    __swig_setmethods__ = {}
    for _s in [PdfListField]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, PdfComboBox, name, value)
    __swig_getmethods__ = {}
    for _s in [PdfListField]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, PdfComboBox, name)
    __repr__ = _swig_repr

    def __init__(self, arg2):
        this = _api.new_PdfComboBox(arg2)
        try:
            self.this.append(this)
        except:
            self.this = this

    def SetEditable(self, bEdit):
        return _api.PdfComboBox_SetEditable(self, bEdit)

    def IsEditable(self):
        return _api.PdfComboBox_IsEditable(self)
    __swig_destroy__ = _api.delete_PdfComboBox
    __del__ = lambda self: None
PdfComboBox_swigregister = _api.PdfComboBox_swigregister
PdfComboBox_swigregister(PdfComboBox)

class PdfButton(PdfField):
    __swig_setmethods__ = {}
    for _s in [PdfField]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, PdfButton, name, value)
    __swig_getmethods__ = {}
    for _s in [PdfField]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, PdfButton, name)
    __repr__ = _swig_repr

    def __init__(self, arg2):
        this = _api.new_PdfButton(arg2)
        try:
            self.this.append(this)
        except:
            self.this = this

    def IsPushButton(self):
        return _api.PdfButton_IsPushButton(self)

    def IsCheckBox(self):
        return _api.PdfButton_IsCheckBox(self)

    def IsRadioButton(self):
        return _api.PdfButton_IsRadioButton(self)

    def SetCaption(self, rsText):
        return _api.PdfButton_SetCaption(self, rsText)

    def GetCaption(self):
        return _api.PdfButton_GetCaption(self)
    __swig_destroy__ = _api.delete_PdfButton
    __del__ = lambda self: None
PdfButton_swigregister = _api.PdfButton_swigregister
PdfButton_swigregister(PdfButton)

class PdfPushButton(PdfButton):
    __swig_setmethods__ = {}
    for _s in [PdfButton]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, PdfPushButton, name, value)
    __swig_getmethods__ = {}
    for _s in [PdfButton]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, PdfPushButton, name)
    __repr__ = _swig_repr

    def __init__(self, arg2):
        this = _api.new_PdfPushButton(arg2)
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _api.delete_PdfPushButton
    __del__ = lambda self: None
PdfPushButton_swigregister = _api.PdfPushButton_swigregister
PdfPushButton_swigregister(PdfPushButton)

class PdfCheckBox(PdfButton):
    __swig_setmethods__ = {}
    for _s in [PdfButton]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, PdfCheckBox, name, value)
    __swig_getmethods__ = {}
    for _s in [PdfButton]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, PdfCheckBox, name)
    __repr__ = _swig_repr

    def __init__(self, arg2):
        this = _api.new_PdfCheckBox(arg2)
        try:
            self.this.append(this)
        except:
            self.this = this

    def SetChecked(self, bChecked):
        return _api.PdfCheckBox_SetChecked(self, bChecked)

    def IsChecked(self):
        return _api.PdfCheckBox_IsChecked(self)
    __swig_destroy__ = _api.delete_PdfCheckBox
    __del__ = lambda self: None
PdfCheckBox_swigregister = _api.PdfCheckBox_swigregister
PdfCheckBox_swigregister(PdfCheckBox)

class PdfString(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, PdfString, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, PdfString, name)
    __repr__ = _swig_repr

    def __init__(self, arg2, pEncoding=None):
        this = _api.new_PdfString(arg2, pEncoding)
        try:
            self.this.append(this)
        except:
            self.this = this

    def GetString(self):
        return _api.PdfString_GetString(self)
    __swig_destroy__ = _api.delete_PdfString
    __del__ = lambda self: None
PdfString_swigregister = _api.PdfString_swigregister
PdfString_swigregister(PdfString)

# This file is compatible with both classic and new-style classes.


